/*
 *
 * InvestPage constants
 *
 */

export const DEFAULT_ACTION = 'app/InvestPage/DEFAULT_ACTION';

export const GET_TOKENS_REQUEST = 'app/InvestPage/GET_TOKENS_REQUEST';
export const GET_TOKENS_SUCCESS = 'app/InvestPage/GET_TOKENS_SUCCESS';
export const GET_TOKENS_ERROR = 'app/InvestPage/GET_TOKENS_ERROR';

export const MINT_GTOKEN_FROM_CTOKEN = 'app/InvestPage/MINT_GTOKEN_FROM_CTOKEN';
export const MINT_GTOKEN_FROM_CTOKEN_SUCCESS = 'app/InvestPage/MINT_GTOKEN_FROM_CTOKEN_SUCCESS';
export const MINT_GTOKEN_FROM_CTOKEN_ERROR = 'app/InvestPage/MINT_GTOKEN_FROM_CTOKEN_ERROR';

export const MINT_GTOKEN_FROM_UNDERLYING = 'app/InvestPage/MINT_GTOKEN_FROM_UNDERLYING';
export const MINT_GTOKEN_FROM_UNDERLYING_SUCCESS = 'app/InvestPage/MINT_GTOKEN_FROM_UNDERLYING_SUCCESS';
export const MINT_GTOKEN_FROM_UNDERLYING_ERROR = 'app/InvestPage/MINT_GTOKEN_FROM_UNDERLYING_ERROR';

export const REDEEM_GTOKEN_TO_CTOKEN = 'app/InvestPage/REDEEM_GTOKEN_TO_CTOKEN';
export const REDEEM_GTOKEN_TO_CTOKEN_SUCCESS = 'app/InvestPage/REDEEM_GTOKEN_TO_CTOKEN_SUCCESS';
export const REDEEM_GTOKEN_TO_CTOKEN_ERROR = 'app/InvestPage/REDEEM_GTOKEN_TO_CTOKEN_ERROR';

export const REDEEM_GTOKEN_TO_UNDERLYING = 'app/InvestPage/REDEEM_GTOKEN_TO_UNDERLYING';
export const REDEEM_GTOKEN_TO_UNDERLYING_SUCCESS = 'app/InvestPage/REDEEM_GTOKEN_TO_UNDERLYING_SUCCESS';
export const REDEEM_GTOKEN_TO_UNDERLYING_ERROR = 'app/InvestPage/REDEEM_GTOKEN_TO_UNDERLYING_ERROR';

export const GET_TOKEN_STATS_REQUEST = 'app/InvestPage/GET_TOKEN_STATS_REQUEST';
export const GET_TOKEN_STATS_SUCCESS = 'app/InvestPage/GET_TOKEN_STATS_SUCCESS';
export const GET_TOKEN_STATS_ERROR = 'app/InvestPage/GET_TOKEN_STATS_ERROR';

export const APPROVE_TOKEN = 'app/InvestPage/APPROVE_TOKEN';
export const APPROVE_TOKEN_SUCCESS = 'app/InvestPage/APPROVE_TOKEN_SUCCESS';
export const APPROVE_TOKEN_ERROR = 'app/InvestPage/APPROVE_TOKEN_ERROR';

export const CHANGE_PAGE = 'app/InvestPage/CHANGE_PAGE';
export const SEARCH = 'app/InvestPage/SEARCH';

